### ISSUE TITLE
[Non-Developers] Workshop: June 13-14, 2023

### ISSUE THREAD

**Issue by RinatS** [im-customers/ge#2]
Add the contact info below:

- First Name/Last Name
- Business email address
- Role in customer org

**Comment by RinatS** [comment]
Rinat Shagisultanov
Technical Director
rinats@infomagnus.com

**Comment by jason-dour-e** [comment]
Jason A. Dour
Enterprise Architect / DT Business Continuity Coordinator
jason.dour@geappliances.com

**Comment by drchil02** [comment]
Doug Childers
Principal Solutions Architect, EDI/API
doug.childers@geappliances.com

**Comment by weigelmj** [comment]
Marla Weigel
Senior Digital Technology Manager - Manufacturing AP4 and AP5
marla.weigel@geappliances.com

**Comment by gkaiser2** [comment]
Gary Kaiser
DT Site Senior Manager
gary.kaiser@geappliances.com

**Comment by Xav345** [comment]
Xavier Armstrong 
IT Security Analyst
xavier.armstrong@geappliances.com

**Comment by jatretter** [comment]
Jeff Tretter
jeff.tretter@geappliances.com
Director - DT Manufacturing
